### PR TITLE
Setting up controllers and addresses

### PR DESCRIPTION
**Pull request by jabdownsmash**
This commit includes some structural decisions:
- Addresses are stored in addr.py _as ints_
  - Get Dolphin string format with addr.toStr()
  - Should be stored as strings instead, with an accompanying toInt()?
  - I was thinking that manipulating addresses might happen often, but I'm not confident there
- Tracking Melee time is done using the global frame count
- MemoryWatcher returns addresses with upper() called
- 'events' are handled entirely in p3.py

I plan to continue by completing events from the controllers, but I want to make sure that I'm doing so in a sensible manner. Thoughts?

### CODE REVIEW

**Comment by spxtr** [comment]
Good, this is something that needs to happen. I'll take a look tomorrow.

**Comment by jabdownsmash** [comment]
I realized this morning that an i/o layer between Python and Melee would have quite a few uses outside of programmatic AI: statistics/analysis, better netplay match recording, TAS automation, etc. I think that p3 should be developed with that in mind, and the AI component should be separate from the i/o.

**Comment by spxtr** [comment]
+1 to keeping things modular so that IO is separate from AI.

Remember that some memory addresses are pointers + offsets, so storing them as a single int isn't going to work so nicely. It might be a good idea to keep them as a dictionary from address strings to their name and use some getattr/setattr magic to make a nice state class. This isn't perfect either because we want to have an array of player state classes so that we don't have fields like player1x, player2x, etc.

**Comment by jabdownsmash** [comment]
Now that you mention it, looking at the [pointer pr](https://github.com/dolphin-emu/dolphin/pull/3413), it's not obvious how that works. What does 140 mean in that specific example?

Perhaps what we need is an address class, since most addresses will have a specific way to be decoded, but some will be decoded in an identical manner as others.

**Comment by spxtr** [comment]
The address `80453130 140` means watch address `(*0x80453130) + 0x140`. It chases the pointer at the first location and goes to the offset in the second. This is necessary because character data is stored as an offset from a pointer at a fixed location.

**Comment by jabdownsmash** [comment]
Ah, that makes a lot of sense.

**Comment by jabdownsmash** [comment]
I've begun adding some functionality to MemoryWatcher in [my fork](https://github.com/sepharoth213/dolphin), once that's done and I submit a pr there there will likely be huge refactors.

**Comment by spxtr** [comment]
I would advise against reading 8-byte ints. The MemoryWatcher runs in a different thread with no concurrency protection. x86 says that word-length chunks of memory operations will be atomic, but we might get corrupted 8-byte reads.

**Comment by jabdownsmash** [comment]
Fiddling with MemoryWatcher with little experience with threads/memory definitely makes me a little nervous. Thanks for the heads-up.

**Comment by spxtr** [comment]
What functionality are you looking at adding? I wanted to keep MemoryWatcher as simple as possible and avoid any post-processing on dolphin's side.

**Comment by jabdownsmash** [comment]
There was discussion in the [MeleeAI](https://github.com/luckycharms14/MeleeAI) Slack channel, and aliasing addresses in Locations.txt was a feature luckycharms and I agreed would simplify things for everyone. Being able to specify 8, 16, or 32 bit reads is something that is helpful and has little overhead in MemoryWatcher. These are all valid entries in Locations.txt in my fork:

```
player 1 percent: 16bits 804530E0
player 2 percent: 80453F70
8bits 804C1FAC
804D7420
```

Dolphin would send 'player 1 percent' instead of '804530E0', etc.

Before I was aware that you could follow multiple offsets I was working on a way to dynamically add and remove addresses from the list of watched addresses via a named pipe, but I'm not so sure that would be useful anymore.

**Comment by jabdownsmash** [comment]
I've looked it over, and you're right. There's definitely no need for more functionality.

**Comment by spxtr** [comment]
Heh, I wouldn't say that. I've had a request to be able to send a message the other way saying "send everything regardless of whether it changed, just once," that I'm looking into implementing.

**Comment by jabdownsmash** [comment]
Well at least, I don't see the need for aliasing and changing bit length in Locations.txt. One idea I had was to accept "REQUEST {addr}" via a named pipe in MemoryWatcher to be able to get one-off reads.

Being able to receive "REFRESH" as well would include the functionality you're talking about.

**Pull request closed without merging**
